export const SEED_SOURCE = [
  {
    id: "tater-tots",
    question: "Will school lunch have tater tots next week?",
    icon: "🥔",
    category: "Food",
    yes: 45,
    no: 55,
    hoursAgo: 72,
  },
  {
    id: "squirrel-pizza",
    question: "Will a squirrel steal pizza at the park this weekend?",
    icon: "🐿️",
    category: "Outdoors",
    yes: 30,
    no: 70,
    hoursAgo: 22,
  },
  {
    id: "coffee-cold",
    question: "Will my coffee get cold before the meeting ends today?",
    icon: "☕",
    category: "Office",
    yes: 64,
    no: 36,
    hoursAgo: 10,
  },
  {
    id: "microwave-sauce",
    question: "Will the office microwave become a crime scene this week?",
    icon: "🍝",
    category: "Office",
    yes: 58,
    no: 42,
    hoursAgo: 40,
  },
  {
    id: "wifi-drop",
    question: "Will Wi‑Fi drop during the important presentation?",
    icon: "📶",
    category: "Tech",
    yes: 51,
    no: 49,
    hoursAgo: 5,
  },
  {
    id: "printer-jam",
    question: "Will the printer jam while the boss is watching?",
    icon: "🖨️",
    category: "Office",
    yes: 72,
    no: 28,
    hoursAgo: 70,
  },
  {
    id: "seagull-lunch",
    question: "Will a seagull steal someone’s fries this weekend?",
    icon: "🦅",
    category: "Outdoors",
    yes: 61,
    no: 39,
    hoursAgo: 18,
  },
  {
    id: "cat-zoom",
    question: "Will my cat cameo on a video call this week?",
    icon: "🐈",
    category: "Home",
    yes: 67,
    no: 33,
    hoursAgo: 12,
  },
] as const;
